name: "platex Action"
author: "mas-tsukuba"
description: "Compile tex file with platex"
inputs:
  LATEX_FILE_NAME:
    description: "Compile Tex File"
    required: true
    default: "main.tex"
  WORKING_DIRECTORY:
    description: "Working directory for compiling tex"
    default: "./"
runs:
  using: "docker"
  image: "Dockerfile"
